### PR TITLE
Pr for first finished component of test_issue_maker.py. 

### PR DESCRIPTION
**Pull request by RobOHt**
Please check for bugs! There must be a tone!

### CODE REVIEW

**Comment by RobOHt** [comment]
Go

> Hello @RobOHt! Thanks for opening this PR.
> 
> * In the file [`test_issue_maker.py`](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py):
> 
> > [Line 5:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py#L5): [F403](https://duckduckgo.com/?q=pep8%20F403) 'from issue_maker import *' used; unable to detect undefined names
> > [Line 16:30](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py#L16): [F405](https://duckduckgo.com/?q=pep8%20F405) 'update' may be undefined, or defined from star imports: issue_maker
> > [Line 20:30](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py#L20): [F405](https://duckduckgo.com/?q=pep8%20F405) 'update' may be undefined, or defined from star imports: issue_maker
> > [Line 24:30](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py#L24): [F405](https://duckduckgo.com/?q=pep8%20F405) 'update' may be undefined, or defined from star imports: issue_maker
> 
> Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)



> Hello @RobOHt! Thanks for opening this PR.
> 
> * In the file [`test_issue_maker.py`](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py):
> 
> > [Line 5:1](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py#L5): [F403](https://duckduckgo.com/?q=pep8%20F403) 'from issue_maker import *' used; unable to detect undefined names
> > [Line 16:30](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py#L16): [F405](https://duckduckgo.com/?q=pep8%20F405) 'update' may be undefined, or defined from star imports: issue_maker
> > [Line 20:30](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py#L20): [F405](https://duckduckgo.com/?q=pep8%20F405) 'update' may be undefined, or defined from star imports: issue_maker
> > [Line 24:30](https://github.com/SwagLyrics/swaglyrics-backend/blob/4726bb7bf9ea4a549a4caaeb68aef97008fdb71b/test_issue_maker.py#L24): [F405](https://duckduckgo.com/?q=pep8%20F405) 'update' may be undefined, or defined from star imports: issue_maker
> 
> Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

Thanks a lot for your help! I just removed the star in imports locally and I'll create a second pr tomorrow with it alongside the second unit test.

**Comment by aadibajpai** [comment]
@RobOHt any updates you make to your branch will automatically be reflected in the PR so you can just make the changes here without starting a new PR. You should also update your fork to the latest master.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by RobOHt** [comment]
Uploaded new change to my own branch.

**Comment by aadibajpai** [comment]
@RobOHt you started this PR from your unittest branch but you added the new tests to the master branch. For the tests to be reflected here, you should add them to the unittest branch (since that is what this PR sees).

Also, can you update your fork with the latest commits to this repo?

**Comment by aadibajpai** [comment]
We integrated this in tests 👍

**Pull request closed without merging**
