### PR TITLE
Add Discord bot for GitHub Star Hook

### PR DESCRIPTION
**Pull request by JamesVStone**
Added a discord bot that posts a rich embed to the `#gh-activity` channel on discord. This update is just focusing on starring. When a user adds a star on GH it will contact the webhook which will trigger the bot to send a message to the discord channel.

I have follow various specification such as the discord developer documentation and the official discord.py docs. :)

### CODE REVIEW

**Comment by JamesVStone** [comment]
@aadibajpai To note I have tested the discord code on my current server bot test but I cannot seem to use my postman client to emulate a discord webhook request. It would be worth testing the code acc posts the message and all is well with the Flask server.

**Comment by JamesVStone** [comment]
I don't think @pep8speaks understands the walrus operator  :laughing: 
```python
:=
```

**Comment by JamesVStone** [comment]
# Progress update
I have now properly implemented the discord bot interface in a new file `discord_bot.py`. As for `issue_maker.py`I have added a method that will trigger the bot when a star is added on the github repo. 

As for the scope of the bot, I see it being just the server housekeeping bot for the SwSpotify discord (if permanent consider generating new bot tokens). I am happy to help maintain both the discord server and the bot for the foreseeable future.

The bot tokens for the discord are handled though environment variable `DISCORD_TOKEN` so set as appropriate.

I will add all this documentation on running the server (token setup etc) to `README.md`if that is ok with you.

Apologies for the hasty submit last time :/
@aadibajpai

**Comment by JamesVStone** [comment]
There is a major error with the code. Only the bot runs.

**Comment by aadibajpai** [comment]
> There is a major error with the code. Only the bot runs.

what do you mean?

**Comment by JamesVStone** [comment]
> > There is a major error with the code. Only the bot runs.
> 
> what do you mean?

Upon import of the `disocrd_bot.py` it runs the discord bot because I had a blocking function in the root of the file. I am having trouble finding a way to start the event loop of the discord bot without blocking in the main server file. (basically the flask app dose not run in my current iteration :/)

**Comment by JamesVStone** [comment]
I am closing this PR as my current approach could not meet the requirements for this project without major changes to the infrastructure. This mostly boils down to the fact that threading and asyncio don't behave or preform well together.

**Pull request closed without merging**
